#! /bin/sh

autostart() {
picom &
feh --bg-scale $HOME/Pictures/glt5.png &
pkill polybar
polybar -c $HOME/.config/polybar/config.ini &
}
autostart

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         4
bspc config window_gap          16

bspc config normal_border_color "#585b70"
bspc config focused_border_color "#b4befe"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_follows_focus true

